//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleOfFaculty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JoinLessonType
    {
        public int Id { get; set; }
        public Nullable<int> LessonId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> Time { get; set; }
    
        public virtual Lesson Lesson { get; set; }
        public virtual Type Type { get; set; }
    }
}
