//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleOfFaculty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lecturer
    {
        public lecturer()
        {
            this.JoinLessonLecturers = new HashSet<JoinLessonLecturer>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string patromic { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<int> qualification { get; set; }
    
        public virtual ICollection<JoinLessonLecturer> JoinLessonLecturers { get; set; }
    }
}
