//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleOfFaculty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lecturer
    {
        public Lecturer()
        {
            this.JoinLessonLecturers = new HashSet<JoinLessonLecturer>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Qualification { get; set; }
    
        public virtual ICollection<JoinLessonLecturer> JoinLessonLecturers { get; set; }
    }
}
