//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleOfFaculty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lesson
    {
        public lesson()
        {
            this.lessonForLecturers = new HashSet<lessonForLecturer>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int time { get; set; }
        public int typeId { get; set; }
    
        public virtual ICollection<lessonForLecturer> lessonForLecturers { get; set; }
        public virtual type type { get; set; }
    }
}
