//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleOfFaculty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profession
    {
        public profession()
        {
            this.lecturerProfessions = new HashSet<lecturerProfession>();
        }
    
        public int id { get; set; }
        public string profession1 { get; set; }
    
        public virtual ICollection<lecturerProfession> lecturerProfessions { get; set; }
    }
}
