//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleOfFaculty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qualification
    {
        public qualification()
        {
            this.lecturers = new HashSet<lecturer>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<lecturer> lecturers { get; set; }
    }
}
