//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleOfFaculty.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScheduleForFacultyEntities : DbContext
    {
        public ScheduleForFacultyEntities()
            : base("name=ScheduleForFacultyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<JoinLessonLecturer> JoinLessonLecturers { get; set; }
        public DbSet<lecturer> lecturers { get; set; }
        public DbSet<Lesson> Lessons { get; set; }
    }
}
