//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleOfFaculty.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class schedulOfFacultyEntities : DbContext
    {
        public schedulOfFacultyEntities()
            : base("name=schedulOfFacultyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<lecturer> lecturers { get; set; }
        public DbSet<lecturerProfession> lecturerProfessions { get; set; }
        public DbSet<lesson> lessons { get; set; }
        public DbSet<lessonForLecturer> lessonForLecturers { get; set; }
        public DbSet<login> logins { get; set; }
        public DbSet<profession> professions { get; set; }
        public DbSet<qualification> qualifications { get; set; }
        public DbSet<type> types { get; set; }
    }
}
